import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { FileText, Download, Loader2, Mail, Sparkles } from "lucide-react";
import { Input } from "@/components/ui/input";

export default function ExportPresentation({ analysis }) {
  const [isOpen, setIsOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [presentation, setPresentation] = useState(null);
  const [emailTo, setEmailTo] = useState("");
  const [emailNote, setEmailNote] = useState("");

  const generatePresentation = async () => {
    setIsGenerating(true);
    try {
      const prompt = `Create an executive presentation summary from this business analysis. Format it as a professional document with clear sections.

ANALYSIS DATA:
Title: ${analysis.title}
Summary: ${analysis.summary}
Key Insights: ${JSON.stringify(analysis.key_insights, null, 2)}
Recommendations: ${JSON.stringify(analysis.recommendations, null, 2)}
Anomalies: ${analysis.anomalies?.join(", ") || "None"}
Metrics: ${JSON.stringify(analysis.metrics, null, 2)}

Create a presentation-ready document with:
- Executive Summary slide
- Key Findings (3-5 bullets)
- Data Insights (with impact levels)
- Recommendations (prioritized)
- Next Steps

Use professional business language. Make it concise and actionable.`;

      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        model: "claude-3-5-sonnet-20241022"
      });

      setPresentation(result);
    } catch (error) {
      console.error("Error generating presentation:", error);
    }
    setIsGenerating(false);
  };

  const downloadPresentation = () => {
    const content = `
# ${analysis.title}
Generated: ${new Date().toLocaleDateString()}

${presentation}

---
Generated by InsightGen.ai - AI Business Analyst
    `.trim();

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${analysis.title.replace(/[^a-z0-9]/gi, '_')}_presentation.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const sendEmail = async () => {
    if (!emailTo.trim()) return;
    
    setIsSending(true);
    try {
      const emailBody = `
<h2>${analysis.title}</h2>
<p><em>Generated on ${new Date().toLocaleDateString()}</em></p>

${emailNote ? `<p><strong>Note:</strong> ${emailNote}</p><hr/>` : ''}

${presentation.split('\n').map(line => {
  if (line.startsWith('# ')) return `<h1>${line.substring(2)}</h1>`;
  if (line.startsWith('## ')) return `<h2>${line.substring(3)}</h2>`;
  if (line.startsWith('### ')) return `<h3>${line.substring(4)}</h3>`;
  if (line.startsWith('- ')) return `<li>${line.substring(2)}</li>`;
  if (line.trim() === '') return '<br/>';
  return `<p>${line}</p>`;
}).join('\n')}

<hr/>
<p><em>Generated by InsightGen.ai - Your AI Business Analyst</em></p>
      `;

      await base44.integrations.Core.SendEmail({
        to: emailTo,
        subject: `Business Insights: ${analysis.title}`,
        body: emailBody,
        from_name: "InsightGen.ai"
      });

      alert("Email sent successfully!");
      setEmailTo("");
      setEmailNote("");
      setIsOpen(false);
    } catch (error) {
      console.error("Error sending email:", error);
      alert("Failed to send email. Please try again.");
    }
    setIsSending(false);
  };

  const handleOpen = () => {
    setIsOpen(true);
    if (!presentation) {
      generatePresentation();
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button
          onClick={handleOpen}
          variant="outline"
          className="border-2 border-indigo-300 hover:bg-indigo-50"
        >
          <FileText className="w-4 h-4 mr-2" />
          Export Report
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-2xl">
            <Sparkles className="w-6 h-6 text-indigo-600" />
            AI-Generated Presentation
          </DialogTitle>
        </DialogHeader>

        {isGenerating ? (
          <div className="flex flex-col items-center justify-center py-12">
            <Loader2 className="w-12 h-12 text-indigo-600 animate-spin mb-4" />
            <p className="text-slate-600">Generating your presentation...</p>
          </div>
        ) : presentation ? (
          <div className="space-y-6">
            <div className="bg-slate-50 rounded-lg p-6 border-2 border-slate-200 max-h-96 overflow-y-auto">
              <div className="prose prose-slate max-w-none">
                {presentation.split('\n').map((line, i) => {
                  if (line.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold mb-3">{line.substring(2)}</h1>;
                  if (line.startsWith('## ')) return <h2 key={i} className="text-xl font-bold mb-2 mt-4">{line.substring(3)}</h2>;
                  if (line.startsWith('### ')) return <h3 key={i} className="text-lg font-semibold mb-2">{line.substring(4)}</h3>;
                  if (line.startsWith('- ')) return <li key={i} className="ml-6">{line.substring(2)}</li>;
                  if (line.trim() === '') return <br key={i} />;
                  return <p key={i} className="mb-2">{line}</p>;
                })}
              </div>
            </div>

            <div className="flex gap-3">
              <Button
                onClick={downloadPresentation}
                className="flex-1 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700"
              >
                <Download className="w-4 h-4 mr-2" />
                Download as Markdown
              </Button>
            </div>

            <div className="border-t pt-6 space-y-4">
              <h3 className="font-semibold flex items-center gap-2">
                <Mail className="w-5 h-5 text-indigo-600" />
                Share via Email
              </h3>
              <div className="space-y-3">
                <div>
                  <Label htmlFor="email">Recipient Email</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="colleague@company.com"
                    value={emailTo}
                    onChange={(e) => setEmailTo(e.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="note">Optional Note</Label>
                  <Textarea
                    id="note"
                    placeholder="Add a personal message..."
                    value={emailNote}
                    onChange={(e) => setEmailNote(e.target.value)}
                    rows={3}
                  />
                </div>
                <Button
                  onClick={sendEmail}
                  disabled={!emailTo.trim() || isSending}
                  className="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700"
                >
                  {isSending ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Sending...
                    </>
                  ) : (
                    <>
                      <Mail className="w-4 h-4 mr-2" />
                      Send Report
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}